### PR TITLE
Less rejection

### LINKED ISSUE #8: Support retries
Currently this lambda tries to download the file, and immediately gives up if anything goes wrong.  Should support timeouts/retries when download gets non-404s.

(May also want to port this logic to the image-lambda).

### PR DESCRIPTION
**Pull request by cavis**
See #8 and #9.  Will still need to add some cloudwatch log metrics to parse/alarm on failures.

May also fix #8 ... just by doing a better job with rejecting "retryable" errors, which results in SNS retrying it a few of times.  (But only a few - then it goes [to the DLQ](http://docs.aws.amazon.com/lambda/latest/dg/retries-on-errors.html) if configured).

- [x] Log all the errors in an easily searchable/countable way
- [x] Only reject errors we want to retry
  - HTTP downloads with status = 502/503/504
  - S3 uploads
  - Any "unknown" errors
- [x] Always copy to destination S3 location, regardless of validation
- [x] Validate video files
  - Added per-stream fields to SQS callback: `audio` and `video`
  - Deprecated other top-level audio SQS callback fields
  - The callback `valid` flag now reflects `audio || video` (ffprobe found audio/video streams)
  - Validation never fails in a way that sets a callback `error` (which is any non-retryable error, like an HTTP 404, or a non-existent S3 file, etc)

### CODE REVIEW

**Comment by kookster** [comment]
@cavis since you're already doing the work now to find audio and video streams from ffprobe, and returning at least a bit of data on each, does an array of stream info make more sense?

File: lib/logger.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+'use strict';
+
+/**
+ * Standard loggers (with prefixes so they're easy to search for)
```
Comment (gcampo88) [inline lib/logger.js]: so handy! http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-logging.html

Comment (gcampo88) [inline lib/logger.js]: so handy! http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-logging.html

File: lib/processor/download.js [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+      result.s3Key = m[2];
+      s3.getObject({Bucket: m[1], Key: m[2]})
+        .createReadStream()
+        .on('error', err => rejectNoRetry(err))
+        .pipe(writeStream);
+    } else if (uploadUrl.match(/^https?:\/\//)) {
+      (uploadUrl.match(/^https/) ? https : http).get(uploadUrl, resp => {
+        if (resp.statusCode !== 200) {
+          let err = new Error(`Got ${resp.statusCode} for url: ${uploadUrl}`);
+          if (resp.statusCode < 500) {
```
Comment (gcampo88) [inline lib/processor/download.js]: why < 500? [ticket](https://github.com/PRX/cms-audio-lambda/issues/8) just said retry on non-404s, no?

File: lib/processor/validate.js [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+  }
+
+  return ffprobePromise.then(
+    info => {
+      let meta = {size: info.format.size, hasAudio: false, hasVideo: false};
+      let audioStream = info.streams.find(s => s.codec_type === 'audio');
+      let videoStream = info.streams.find(s => s.codec_type === 'video' && s.duration > 0);
+
+      // audio stream info
+      if (audioStream) {
```
Comment (gcampo88) [inline lib/processor/validate.js]: before there was another check for mp2/mp3 in addition to checking for codec_type 'audio' -- no longer necessary?

File: lib/uploaded-file.js [hunk 4]
```diff
@@ -13,14 +13,18 @@ module.exports = class UploadedFile {
...
-    this.size      = null; // in bytes
-    this.format    = null; // codec name
-    this.bitrate   = null; // 64/128/256
-    this.frequency = null; // float 44.10 / 48.00 / etc
-    this.channels  = null; // number of channels
-    this.layout    = null; // mono/stereo/etc
+    // audio/video metadata
+    this.hasAudio    = null;
+    this.duration    = null; // in seconds, ROUNDED UP
+    this.durationMs  = null; // in milliseconds
```
Comment (gcampo88) [inline lib/uploaded-file.js]: just a nice to have? or you lookin at https://github.com/PRX/cms.prx.org/issues/314 ?

File: lib/processor/index.js [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+      exports.validate(file.localPath),
+      exports.uploadAndCopy(file)
+    ]);
+  }).then(results => {
+    file.setValidated(results[0]);
+    file.setProcessed(results[1]);
+    return file.callback().then(() => true);
+  }).catch(err => {
+    if (err.noRetry) {
+      logger.warn(err.message);
```
Comment (gcampo88) [inline lib/processor/index.js]: any reason to be more explicit here in the logs and say "not retrying" along with error message?

File: lib/processor/download.js [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+
+    if (!uploadUrl) {
+      rejectNoRetry(new Error('No url set for event'));
+    } else if (uploadUrl.startsWith('s3://')) {
+      let m = uploadUrl.match(/s3:\/\/([^\/]+)\/(.*)/);
+      result.s3Bucket = m[1];
+      result.s3Key = m[2];
+      s3.getObject({Bucket: m[1], Key: m[2]})
+        .createReadStream()
+        .on('error', err => rejectNoRetry(err))
```
Comment (gcampo88) [inline lib/processor/download.js]: in your comment on this PR it sounded like we do want to retry S3 upload errors? 
```
Only reject errors we want to retry
- HTTP downloads with status >= 500
- S3 uploads
```

File: lib/logger.js (hunk 1 above)
Comment (cavis) [reply lib/logger.js]: Yeah, and what they don't tell you is that it's pretty much impossible to find your log statements in CW without some obvious prefix like `[INFO]`.  Too much other noise in there, as it logs every lambda execution, how much memory/time it used, how much you were billed for, etc.

File: lib/processor/download.js (hunk 2 above)
Comment (cavis) [reply lib/processor/download.js]: So specifically, I want to retry 502/503/504 errors, as they indicate some sort of temporary problem upstream that _might_ resolve itself if I retry it.  (And experience has told me that S3 can periodically throw those).

Generally... any >= 500 is unexpected, and might change with a retry, whereas anything less than that won't.  But as I'm typing this, it's starting to sound like it might be better if I call out the statuses specifically.  Okay fine, you've talked me into it.

File: lib/processor/validate.js (hunk 3 above)
Comment (cavis) [reply lib/processor/validate.js]: Yeah, I think we're moving that logic out of the lambda - it's responsible for returning info, but not making any judgements based on that.

File: lib/uploaded-file.js (hunk 4 above)
Comment (cavis) [reply lib/uploaded-file.js]: Both!  In the spirit of not generalizing data here ... will leave it up to CMS to do that in the future.

File: lib/processor/index.js (hunk 5 above)
Comment (cavis) [reply lib/processor/index.js]: I figured this was the only `[WARN]` at the moment.  But yeah - I should probably make that more explicit.  Will do!

File: lib/processor/download.js (hunk 6 above)
Comment (cavis) [reply lib/processor/download.js]: Yeah, but this is the download!

Also, I'm actually not sure how to differentiate "not found / not authorized / timeout" errors returned by S3 here.  I'm hoping that by throwing/logging them, I can figure that out and retry only the timeouts here at some point.

File: lib/logger.js (hunk 1 above)
Comment (gcampo88) [reply lib/logger.js]: :no_mouth:

File: lib/processor/download.js (hunk 2 above)
Comment (gcampo88) [reply lib/processor/download.js]: glad to be of help here

File: lib/processor/validate.js (hunk 3 above)
Comment (gcampo88) [reply lib/processor/validate.js]: 👍

File: lib/uploaded-file.js (hunk 4 above)
Comment (gcampo88) [reply lib/uploaded-file.js]: 👍

File: lib/processor/download.js (hunk 6 above)
Comment (gcampo88) [reply lib/processor/download.js]: oops!

File: lib/processor/index.js [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+
+// do all the things
+exports.work = (audioEvent) => {
+  let file = new UploadedFile(audioEvent);
+
+  // process file - catch most errors
+  return exports.download(audioEvent.audioUploadPath).then(data => {
+    file.setDownloaded(data);
+    return Q.all([
+      exports.validate(file.localPath),
```
Comment (kookster) [inline lib/processor/index.js]: is it validating? more like analyzing now, or probing (that sounds wrong)

File: lib/processor/upload.js [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+
+  let uploadOriginal;
+  if (file.s3Bucket && file.s3Key) {
+    uploadOriginal = s3Copy(file.s3Bucket, file.s3Key, dest, type);
+  } else {
+    uploadOriginal = localUpload(file.localPath, dest, type);
+  }
+
+  let fileParts = path.parse(file.name);
+  let fileCopies = COPY_VARIATIONS.map(vary => {
```
Comment (kookster) [inline lib/processor/upload.js]: If this part of cms was a bit smarter, could avoid needing to make `_broadcast` copy of the file:
https://github.com/PRX/cms.prx.org/blob/master/app/representers/api/audio_file_representer.rb#L29

File: lib/mimes.js [hunk 9]
```diff
@@ -0,0 +1,39 @@
...
+  if (['mp1', 'mp2', 'mp3', 'mpg', 'mpeg'].indexOf(format) > -1) {
+    return 'audio/mpeg';
+  } else if (['mp4', 'm4a'].indexOf(format) > -1) {
+    return 'audio/mp4';
+  } else if (format) {
+    logger.warn(`Unknown mime audio: ${format}`);
+    return `audio/${format}`;
+  } else {
+    return 'application/octet-stream';
+  }
```
[the remark this answers is not in the document]
Comment (cavis) [reply lib/mimes.js]: I'll open a ticket to support them.  (Easier to test those in a separate PR).

File: lib/processor/index.js (hunk 7 above)
Comment (cavis) [reply lib/processor/index.js]: Yeah, you're right.  It doesn't ever "fail" validation, so it's more like "detection" now.  I'd rather not rename it here, since there's already so much going on.  But I could rename callback `valid` key, if you want?  (Or add a new one, to maintain backwards compatibility?)

File: lib/processor/download.js [hunk 10]
```diff
@@ -0,0 +1,61 @@
...
+        .pipe(writeStream);
+    } else if (uploadUrl.match(/^https?:\/\//)) {
+      (uploadUrl.match(/^https/) ? https : http).get(uploadUrl, resp => {
+        if (resp.statusCode !== 200) {
+          let err = new Error(`Got ${resp.statusCode} for url: ${uploadUrl}`);
+          if ([502, 503, 504].indexOf(resp.statusCode) > -1) {
```
[the remark this answers is not in the document]
Comment (cavis) [reply lib/processor/download.js]: Agreed - will add 500 into that.

File: lib/processor/download.js [hunk 11]
```diff
@@ -0,0 +1,61 @@
...
+      }
+    });
+
+    if (!uploadUrl) {
+      rejectNoRetry(new Error('No url set for event'));
+    } else if (uploadUrl.startsWith('s3://')) {
+      let m = uploadUrl.match(/s3:\/\/([^\/]+)\/(.*)/);
+      result.s3Bucket = m[1];
+      result.s3Key = m[2];
+      s3.getObject({Bucket: m[1], Key: m[2]})
```
[the remark this answers is not in the document]
Comment (cavis) [reply lib/processor/download.js]: Readability++

**Comment by cavis** [comment]
Fallout tickets: #12, #13, #14, PRX/cms-image-lambda#5.

@gcampo88 per (b) ... the README does indicate the new value is in milliseconds.  But yes ... need to make sure we get that into CMS.

**Comment by pkarman** [comment]
blocked by lack of time (deployment requires manual watching of env)

**Comment by cavis** [comment]
Merging this -> will work through the lambda deploy/verification manually.
